### ISSUE TITLE
[Feature/UI] 사용자 상세정보 

### ISSUE THREAD

**Issue by yusonghyeon** [movester/movester_client_backoffice#17]
## 작업 내용 
- 사용자 상세정보 UI

## 요구 사항 
- 기존 컴포넌트 재 사용

![image](https://user-images.githubusercontent.com/81687138/149896281-8dec753a-61c3-42a6-bf39-bf60bdc8a8fd.png)

## 예상 시간
- 3h

**Comment by jnhro1** [comment]
오 3시간...ㅎㅎㅎㅎㅎ 엄청나시네요👍
