### ISSUE TITLE
[백오피스] FE팀 탈주로 인해 작업진행도 확인하기

### ISSUE THREAD

**Issue by hiYong94** [movester/movester_client_backoffice#65]
[Summary]

작성은 노션으로 작성 후 링크 공유
전체 기능 목록화 후 현재까지 구현된 기능 확인
기능 확인 항목은 UI구현과 API 연동으로 나눔
ex) 찜하기
UI 구현 o
API 연동 x

**Comment by jnhro1** [comment]
<img width="1225" alt="164234437-313819fa-47b4-4f77-9378-54431a2a610e" src="https://user-images.githubusercontent.com/57309520/167576092-0c1ea64d-5fc5-4701-b458-c338d2ab62a1.png">

**Comment by jnhro1** [comment]
이미지로 대체하겠습니다.👍
